#!/bin/bash

# ============================================================
# RAMESH POLISETTY — Supabase Setup Script
# This script sets up everything automatically using Supabase CLI
# ============================================================

set -e

echo "🏋️ Ramesh Polisetty — Supabase Setup"
echo "======================================"
echo ""

# Check if Supabase CLI is installed
if ! command -v supabase &> /dev/null; then
    echo "❌ Supabase CLI not found. Installing..."
    echo ""
    echo "Please install Supabase CLI first:"
    echo "  npm install -g supabase"
    echo ""
    echo "Or visit: https://supabase.com/docs/guides/cli"
    exit 1
fi

echo "✅ Supabase CLI found: $(supabase --version)"
echo ""

# Check if already logged in
echo "Checking Supabase login status..."
if ! supabase projects list &> /dev/null; then
    echo "❌ Not logged in. Please login first:"
    echo "  supabase login"
    exit 1
fi

echo "✅ Logged in to Supabase"
echo ""

# Ask for project details
echo "📝 Enter your Supabase project details:"
echo ""

read -p "Project ID (from Supabase dashboard): " PROJECT_ID
read -p "Project URL (e.g., https://xyzcompany.supabase.co): " PROJECT_URL
read -p "Admin email (for admin user): " ADMIN_EMAIL
read -sp "Admin password: " ADMIN_PASSWORD
echo ""

if [ -z "$PROJECT_ID" ] || [ -z "$PROJECT_URL" ] || [ -z "$ADMIN_EMAIL" ] || [ -z "$ADMIN_PASSWORD" ]; then
    echo "❌ All fields are required"
    exit 1
fi

echo ""
echo "🔧 Configuration:"
echo "   Project ID: $PROJECT_ID"
echo "   Project URL: $PROJECT_URL"
echo "   Admin Email: $ADMIN_EMAIL"
echo ""

# Link to Supabase project
echo "🔗 Linking to Supabase project..."
supabase link --project-ref "$PROJECT_ID"

# Run database migrations
echo "🗄️ Running database migrations..."
supabase db push

# Create storage bucket
echo "📦 Creating storage bucket..."
supabase storage create-bucket photos --public

# Create admin user
echo "👤 Creating admin user..."
echo "Note: You may need to create the admin user manually in Supabase Auth UI"
echo "Go to: $PROJECT_URL → Authentication → Users → Add User"
echo "Email: $ADMIN_EMAIL"
echo "Password: $ADMIN_PASSWORD"
echo "Email Confirm: Auto-confirm"
echo ""

# Update configuration files
echo "📝 Updating configuration files..."

# Update js/supabase-config.js
cat > js/supabase-config.js << EOF
/* ============================================================
   RAMESH POLISETTY — Supabase Configuration
   Auto-generated by setup script
   ============================================================ */

const SUPABASE_CONFIG = {
  url: '$PROJECT_URL',
  anonKey: 'YOUR_ANON_KEY',  // Get this from Supabase dashboard → Settings → API
  bucketName: 'photos',
  tableName: 'photos'
};

let supabaseClient = null;

function initSupabase() {
  if (typeof window.supabase !== 'undefined' && SUPABASE_CONFIG.url !== 'YOUR_SUPABASE_URL') {
    supabaseClient = window.supabase.createClient(
      SUPABASE_CONFIG.url,
      SUPABASE_CONFIG.anonKey
    );
    return true;
  }
  return false;
}

window.SUPABASE_CONFIG = SUPABASE_CONFIG;
window.initSupabase = initSupabase;
window.getSupabaseClient = () => supabaseClient;
EOF

echo "✅ Configuration files updated"
echo ""

# Generate .env file for reference
cat > .env << EOF
# Supabase Configuration
SUPABASE_PROJECT_ID=$PROJECT_ID
SUPABASE_URL=$PROJECT_URL
SUPABASE_ANON_KEY=YOUR_ANON_KEY_HERE
ADMIN_EMAIL=$ADMIN_EMAIL

# Get your anon key from:
# $PROJECT_URL → Settings → API → anon/public key
EOF

echo "✅ Environment file created (.env)"
echo ""

echo "======================================"
echo "🎉 Setup Complete!"
echo "======================================"
echo ""
echo "Next steps:"
echo ""
echo "1. Get your anon key from Supabase:"
echo "   $PROJECT_URL → Settings → API → anon/public key"
echo ""
echo "2. Update js/supabase-config.js with your anon key"
echo ""
echo "3. Create admin user in Supabase Auth:"
echo "   $PROJECT_URL → Authentication → Users → Add User"
echo "   Email: $ADMIN_EMAIL"
echo "   Password: (the one you entered)"
echo "   Email Confirm: Auto-confirm"
echo ""
echo "4. Open admin.html in your browser"
echo "   Login with your admin email and password"
echo ""
echo "5. Upload your first photo!"
echo ""
echo "📖 For detailed instructions, see SUPABASE_SETUP.md"
echo ""
